apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      priorityClassName: high-priority
      containers:
        - name: frontend
          image: yellaiahdocker/frontend-k8ss
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MODE
              value: production
            - name: VITE_API_URL
              value: api-load-balancer-service
       
